accounting_group=group_cms
cmssw = /cms/ldap_home/sjws5411/workspace-ui20/rpc-geom/validation-existing/$(geometry)/CMSSW_15_1_0_pre1
output_dir = root://cms-xrdr.private.lo:2094//xrd/store/user/joshin/rpc-geom/validation-existing/$(era)/$(geometry)

JobBatchName = rpc-geom-val-$(era)-$(geometry)
universe = vanilla
getenv = True

transfer_executable = True
executable = run/$(era)/executable.sh

should_transfer_files = YES
transfer_input_files = run/$(era)/step1.py, run/$(era)/step2.py, run/$(era)/step3.py, run/$(era)/step4.py

arguments = $(Process) $(cmssw) $(output_dir) step1.py step2.py step3.py step4.py

output = log/$(era)/$(geometry)/$(Process).out
error = log/$(era)/$(geometry)/$(Process).err
log = log/$(era)/$(geometry)/$(Process).log

when_to_transfer_output = ON_EXIT

+SingularityBind = "/cvmfs, /cms/ldap_home/sjws5411/"
+SingularityImage = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el9:x86_64"

+MaxRuntime = 10800
request_memory = 8192

queue 100