accounting_group=group_cms
cmssw = /cms/ldap_home/sjws5411/workspace-ui20/rpc-geom/validation/$(geometry)/CMSSW_15_0_0
output_dir = root://cms-xrdr.private.lo:2094//xrd/store/user/joshin/rpc-geom/validation/$(eta)/$(geometry)

JobBatchName = rpc-geom-val-$(eta)-$(geometry)
universe = vanilla
getenv = True

transfer_executable = True
executable = run/$(eta)/executable.sh

should_transfer_files = YES
transfer_input_files = run/$(eta)/step1.py, run/$(eta)/step2.py, run/$(eta)/step3.py, run/$(eta)/step4.py

arguments = $(Process) $(cmssw) $(output_dir) step1.py step2.py step3.py step4.py

output = log/$(eta)/$(geometry)/$(Process).out
error = log/$(eta)/$(geometry)/$(Process).err
log = log/$(eta)/$(geometry)/$(Process).log

when_to_transfer_output = ON_EXIT

+SingularityBind = "/cvmfs, /cms/ldap_home/sjws5411/"
+SingularityImage = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el9:x86_64"

+MaxRuntime = 43200
request_memory = 16384

queue 100