accounting_group=group_cms

JobBatchName = $(job_name)
universe = vanilla

getenv = True
transfer_executable = True
executable = executable.sh

transfer_input_files = /tmp/x509up_u556951266
arguments = $(process) $(cmssw_path) $(config_path) $(output_path)

output = log/$(job_name)/process-$(process).out
error = log/$(job_name)/process-$(process).err
log = log/$(job_name)/process-$(process).log

when_to_transfer_output = ON_EXIT

+MaxRuntime = 43200
request_memory = 16384

queue 100